image:
  repository: quay.io/redhat_pe_workshop/parasol-store-db
  pullPolicy: IfNotPresent
  tag: "latest"

pgsql:
  user: parasol
  password: parasol
  database: parasol
  adminPassword: 
  debeziumPassword: debezium

persistence:
  mode: ephemeral