replicaCount: 1

image:
  repository: quay.io/redhat_pe_workshop/parasol-store-db
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  portName: postgresql
  port: 5432
  containerPort: 5432

resources:
  limits:
    cpu: 200m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 128Mi

pgsql:
  user: parasol
  password: parasol
  database: parasol
  adminPassword: 
  debeziumPassword: debezium

persistence:
  mode: ephemeral
  capacity: 20Gi

nodeSelector: {}

tolerations: []

affinity: {}
