---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ parasol_db_argocd_name }}
  namespace: {{ parasol_db_argocd_namespace }}
  labels:
    rht-gitops.com/argocd: {{ parasol_db_argocd_name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: {{ parasol_db_repo_url }}
    targetRevision: {{ parasol_db_repo_revision }}
    path: ./app/helm/parasol-db
    helm:
      valuesFiles:
        ./values/values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ parasol_db_namespace }}
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: {{ parasol_db_argocd_namespace }}
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
